---
- name: Setup group
  group: name={{storm_group}} system=yes

- name: Setup user
  user: name={{storm_user}} system=yes group={{storm_group}}

- name: Create Storm root directory
  file: path={{storm_root_dir}} state=directory owner={{storm_user}} group={{storm_group}} mode=755

- name: Fetch storm package
  get_url: dest=/opt/apache-storm-{{storm_version}}.tar.gz url="{{apache_mirror}}/storm/apache-storm-{{storm_version}}/apache-storm-{{storm_version}}.tar.gz" timeout=120

- name: Uncompress the storm tar
  unarchive: copy=no creates=/opt/apache-storm-{{storm_version}} dest={{storm_root_dir}} src=/opt/apache-storm-{{storm_version}}.tar.gz

- name: Create Storm log and local directories
  file: path={{item}} state=directory owner={{storm_user}} group={{storm_group}} mode=775
  with_items:
    - "{{storm_local_dir}}"
    - "/var/log/storm"

- name: Check if Storm log directory already exists
  stat: path={{storm_root_dir}}/apache-storm-{{storm_version}}/logs get_md5=False
  register: storm_logs_dir

- name: Create Storm log symlink to /var/log/storm if directory does not exist
  file: path={{storm_root_dir}}/apache-storm-{{storm_version}}/logs state=link src=/var/log/storm
  when: not storm_logs_dir.stat.exists
