---
- name: Add mappings to /etc/hosts
  lineinfile: dest=/etc/hosts line='{{ item.ip }} {{ item.name }}' state=present
  with_items:
    - { name: zookeeper, ip: 192.168.33.100 }
    - { name: nimbus, ip: 192.168.33.101 }
    - { name: supervisor1, ip: 192.168.33.102 }
    - { name: supervisor2, ip: 192.168.33.103 }
